# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SweetDeal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SweetDeal
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'

  target 'SweetDealTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SweetDealUITests' do
    # Pods for testing
  end

end
